name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull ${{secrets.DOCKER_USERNAME}}/api-securx:latest

      - name: Delete Old Container
        run: sudo docker container rm -f api-securx || true

      - name: Run Docker Container
        run: sudo docker run -d -p 3001:3001 -v /home/ubuntu/apienv/.env:/app/environment/.env --name api-securx ${{secrets.DOCKER_USERNAME}}/api-securx:latest
