name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clean up Docker (Free up disk space)
        run: sudo docker system prune -f

      - name: Pull Docker image
        run: sudo docker pull ${{secrets.DOCKER_USERNAME}}/api-securx:latest

      - name: Delete Old Container
        run: sudo docker container rm -f api-securx || true

      - name: Run Docker Container
        run: |
          sudo docker run -d \
            -p 3001:3001 \
            --name api-securx \
            -e MONGO="${{secrets.MONGO}}" \
            -e ENCRYPTION_KEY="${{secrets.ENCRYPTION_KEY}}" \
            -e SECRET_KEY="${{secrets.SECRET_KEY}}" \
            -e CLIENT_URL="${{secrets.CLIENT_URL}}" \
            ${{secrets.DOCKER_USERNAME}}/api-securx:latest
